name: Setup

inputs:
  use-cache:
    description: Restore global `~/.npm` cache
    default: 'true'
    required: true

runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      id: setup-node

      with:
        cache: ${{ inputs.use-cache == 'true' && 'npm' || '' }}
        node-version-file: .nvmrc
